name: Buy
on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  buy:
    name: Just Buy Stuff
    concurrency: buy
    permissions:
      contents: read
      packages: read
    env:
      ENV: DEV
      ALPACA_ENPOINT: ${{ secrets.ALPACA_ENPOINT }}
      ALPACA_KEY_ID: ${{ secrets.ALPACA_KEY_ID }}
      ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Buy
        run: python main.py --symbols FNGU=\$10 SVIX=1
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Buy ${{GITHUB_RUN_ID}}
